version: '2'

services:
  randomthings:
    build: .
    expose:
     - 80
    environment:
      NODE_ENV: production
    restart: always


  sevenam:
    build: ../7am
    environment:
      PORT: 80
    restart: always

  haproxy:
    build:
      context: ./haproxy
    links:
     - randomthings
     - sevenam
    ports:
     - "80:80"
    expose:
     - 80
    restart: always
