version: '2'

services:
  randomthings:
    build: .
    expose:
      - 80
    environment:
      NODE_ENV: production
    restart: always


  sevenam:
    build: ../7am
    expose:
      - 8080
    restart: always

  haproxy:
    build:
      context: ./haproxy
    links:
      - randomthings
      - sevenam
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    volumes:
      - /etc/letsencrypt:/srv/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    environment:
      CERTS: 7am.randomthings.io,randomthings.io
      EMAIL: jerryw@gmail.com
    restart: always

