randomthings:
  image: ghost
  expose:
   - 2368
  volumes:
    - /home/ghost:/var/lib/ghost
  environment:
    NODE_ENV: production

sevenam:
  image: 7am
  environment:
    PORT: 80

haproxy:
  image: haproxy
  volumes:
    - /etc/haproxy:/usr/local/etc/haproxy
  links:
   - randomthings
   - sevenam
  ports:
   - "80:80"
  expose:
   - 80

