version: '3'

services:
  traefik:
    image: traefik
    # command: --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    networks:
      - default
    cap_drop:
      - all
    cap_add:
      - net_bind_service
